### ISSUE TITLE
Нормальное отображение проектов

### ISSUE THREAD

**Issue by khmaralex** [LeagueOfDevelopers/LodFrontend#37]
На страницах "Главная", "Разработчики", "Проекты" .

**Comment by Sovent** [comment]
предлагаю вместо геморроя с выравниванием  написать маленькую функцию для расчёта количества проектов, которые отображать на главной: брать ширину экрана, делить её на ширину блока, усекать дробную часть, выбрать, что меньше 3 или то, что получилось.
var pageSize = getPageSize();
var blockSize = getBlockSize();
var blockCount = Math.floor(pageSize / blockSize);
return Math.min(blockCount, 3);

**Comment by khmaralex** [comment]
Эмм, как быть с проектами на странице проектов, и с проектами в портфолио?  Можно сделать по другому, с помощью flexbox вроде, но для этого надо разобраться как это работает.

**Comment by IPRIT** [comment]
Саня, реши проблему с помощью flexbox наконец.
