### ISSUE TITLE
Сделать склонение существительных после цифр для даты регистрации разработчика

### ISSUE THREAD

**Issue by Sovent** [LeagueOfDevelopers/LodFrontend#51]
http://htmler.ru/2013/11/22/sklonenie-chislitelnah-na-javascript/

**Comment by IPRIT** [comment]
А причем здесь числительные? Кстати, вот с этим, что ты имел ввиду, хорошо эта библиотека справляется http://momentjs.com/ Можно выбрать русскую локализацию
