### ISSUE TITLE
Редизайн страниц подтверждения

### ISSUE THREAD

**Issue by Sovent** [LeagueOfDevelopers/LodFrontend#74]

**Comment by khmaralex** [comment]
http://momentjs.com/

**Comment by khmaralex** [comment]
![lodsite-confirmation-error](https://cloud.githubusercontent.com/assets/10733718/14031948/7f922c86-f220-11e5-8df0-4041b956f850.jpg)
![lodsite-confirmation-success](https://cloud.githubusercontent.com/assets/10733718/14031949/7f966864-f220-11e5-8cd6-6f4b0fc0cc60.jpg)
