### ISSUE TITLE
Макет страницы разработчиков

### ISSUE THREAD

**Issue by Sovent** [LeagueOfDevelopers/LodFrontend#8]

**Comment by khmaralex** [comment]
images: 
1) https://drive.google.com/file/d/0B8-HkwlTgqoVMVFBZkpLVHA0SVU/view?usp=sharing
2) https://drive.google.com/file/d/0B8-HkwlTgqoVWEJ6dU5mOXFfTlU/view?usp=sharing
3) https://drive.google.com/file/d/0B8-HkwlTgqoVWXJwRGxybzlOR2s/view?usp=sharing
