### ISSUE TITLE
Макет профиля разработчика

### ISSUE THREAD

**Issue by Sovent** [LeagueOfDevelopers/LodFrontend#9]
Варианты
а) для гостя
б) для разработчика
в) для администратора

**Comment by ikkizento** [comment]
Для гостя: https://vk.com/doc27443385_437037169?hash=3bb2ff3f7c40bbcb75&dl=f98096515deccf9296

Для разработчика: https://vk.com/doc27443385_437037172?hash=8e3cc01fa7b3ab8bb0&dl=67b46bc60276915da3

Для владельца: 
С открытыми оповещениями:https://vk.com/doc27443385_437037183?hash=55e83b64a86559ba1d&dl=084cf16f459a683535
Со скрытыми оповещениями: https://vk.com/doc27443385_437037181?hash=7632a4368c9027b038&dl=0e3d2964959f90d1b4

Портфолио:
Пустое:https://vk.com/doc27443385_437037171?hash=e62b64a457c4c2e644&dl=cd2deea2ee1b3d49fb (гифка - http://rs180.pbsrc.com/albums/x71/saccillia/emotes/Tumbleweed_Emote_V2_0-1.gif~c200)
Не пустое (с наведенной мышкой на 3 проекта: готовый, в процессе, замороженный):https://vk.com/doc27443385_437037170?hash=022ab65f83cb3dc08d&dl=4ca29b034eed6a8819

Состояние разработчика:
Есть проект: https://vk.com/doc27443385_437037173?hash=0242a99de0a72fdc29&dl=b25266a10d13b957ec
Нет проекта: https://vk.com/doc27443385_437037174?hash=4b3481ff233358fccf&dl=ea8c2c3f79a2f3edd8

**Comment by Sovent** [comment]
Не нужно показывать гостям, что они чего-то не видят, в профиле не надо приглашения зарегистрироваться, не надо говорить про какие-то статусы у проектов. Просто показывай, что им нужно видеть и всё.

**Comment by Sovent** [comment]
Плашка с оповещениями в закрытом состоянии будет закрывать фотографию.
Всё таки не "3 портфолио", а "3 проекта" или "Портфолио: 3 проекта"

**Comment by khmaralex** [comment]
images:
а) https://drive.google.com/file/d/0B8-HkwlTgqoVLWU4b2ZidjlpckE/view?usp=sharing
б) https://drive.google.com/file/d/0B8-HkwlTgqoVeGJIX3d6T0VfQzA/view?usp=sharing
в) https://drive.google.com/file/d/0B8-HkwlTgqoVamRNbU5hVGpISkU/view?usp=sharing
